### ISSUE TITLE
Doesn't support github 2-factor authentication

### ISSUE THREAD

**Issue by mattcarabine** [oxygenxml/webapp-github-plugin#4]
We are using Oxygen WebAuthor to update files using git. 

This works well for most users, but we have found that users with 2 factor authentication enabled are unable to commit or create branches:

![image](https://cloud.githubusercontent.com/assets/5352963/22788317/589ed11a-eed7-11e6-8c31-f95d4217f26d.png)

Removing 2-factor authentication allows the app to work as expected.

Would it be possible to add support for 2 factor authentication to this plugin in future?

**Comment by mattcarabine** [comment]
Sometimes the error message changes too:

![image](https://cloud.githubusercontent.com/assets/5352963/22788439/bd761698-eed7-11e6-8358-636324e8b8a1.png)

**Comment by ggbt** [comment]
The plugin supports 2FA, but it only works with GitHub. Fortunately it looks like you are using GitHub.

To enable GitHub Authentication (And at the same time 2FA) you need to follow the instructions found here [1]. After following these steps, the login dialog will present a "Login with GitHub" button which you should use.

[1] https://www.oxygenxml.com/doc/versions/18.1.0/ug-webauthor/topics/webapp-integrate-github-plugin.html?hl=github

**Comment by mattcarabine** [comment]
Ah fantastic, must have missed that, thank you very much!
